GreenspaceRecods
diwise/integration-cip-gbg-karta pull request #1
Opened 2022-11-29 15:23 UTC by mats-dahlberg-goteborg

2022-11-29 16:50 UTC, istyf requested changes
Det finns ett par saker här som borde tittas på innan vi driftsätter den här tjänsten.

2022-11-29 16:50 UTC, istyf commented on cmd/integration-cip-gbg-karta/main.go
> +	}
... else we should output an error to notify the user that the configuration is wrong. This silently fails if you misspel the bc name.

2022-11-29 16:50 UTC, istyf commented on internal/pkg/application/contextbroker.go
> +		log.Info().Msgf("found %d GreenspaceRecords", len(gr))
om err != nil så har du inte fått några gr och borde propagera upp err till anropar med return nil, err

2022-11-29 16:50 UTC, istyf commented on cmd/integration-cip-gbg-karta/main.go
> +	flag.StringVar(&bcSelector, "bcSelector", "greenspacerecord", "Flag to distinguish which funcion to be selected for its business case")
default value här borde vara beach eftersom tjänsten redan används av det projektet och den här ändringen gör att vi inte längre blir kompatibla

2022-11-29 16:50 UTC, istyf commented on cmd/integration-cip-gbg-karta/main.go
tag bort utkommenderad kod

2022-11-29 16:50 UTC, istyf commented on cmd/integration-cip-gbg-karta/main.go
> +			logger.Error().Err(err).Msg("error in bcWaterQualityObserved")
copy paste error

2022-11-29 16:50 UTC, istyf commented on cmd/integration-cip-gbg-karta/main.go
> +			logger.Info().Msgf("updated soilmoisture pressure value for %s (%s)", lon, lat)
Varför är latituden i en parentes?

2022-11-30 08:32 UTC, istyf requested changes
Några detaljer till.

2022-11-30 08:32 UTC, istyf commented on cmd/integration-cip-gbg-karta/main.go
> +	}
Use Fatal here to clearly signal that we are unable to do anything with the supplied configuration. Also, "no configuration found" implies an internal error, while "%s is not a supported business case" is more clear that the supplied configuration is wrong.

2022-11-30 08:32 UTC, istyf commented on cmd/integration-cip-gbg-karta/main.go
> +			logger.Info().Msgf("updated soilmoisture pressure value for %f %f", lon, lat)
What information does this log output really supply? Who wants to see the coordinates in the log and why?

2022-11-30 08:32 UTC, istyf commented on internal/pkg/application/contextbroker.go
> +	} else {
Idiomatic go tries to keep the happy path left aligned. Remove the else here.

2022-11-30 08:32 UTC, istyf commented on internal/pkg/application/contextbroker.go
> +		log.Info().Msgf("found %d GreenspaceRecords", len(gr))
This is already logged by the caller, so you end up logging it twice.

2022-12-05 13:11 UTC, istyf requested changes
En liten detalj till ...

2022-12-05 13:11 UTC, istyf commented on cmd/integration-cip-gbg-karta/main.go
> +		logger.Fatal().Err(err).Msg("%s is not a supported business case" + bcSelector)
Använd Msgf om du vill använda %s, annars Msg(bcSelector + " is not ...")

2022-12-05 13:11 UTC, istyf commented on cmd/integration-cip-gbg-karta/main.go
> +			logger.Info().Msgf("updated soilmoisture pressure into geodata_markfukt.greenspacerecord")
Använd Msg() om du inte skall formatera en sträng

2022-12-05 13:39 UTC, istyf requested changes

2022-12-05 13:39 UTC, istyf commented on cmd/integration-cip-gbg-karta/main.go
> +		logger.Fatal().Err(err).Msgf("%s is not a supported business case" + bcSelector)
", bcSelector

2022-12-05 13:41 UTC, mats-dahlberg-goteborg commented on cmd/integration-cip-gbg-karta/main.go
> +		logger.Fatal().Err(err).Msgf("%s is not a supported business case" + bcSelector)
Updated

2022-12-05 13:51 UTC, istyf approved these changes
/lgtm

2022-12-05 13:52 UTC, merged